[package]
name = "egraph"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ascent = "*"
egg = "0.9.1"
itertools = "0.10.5"
petgraph = "0.6.2"
